version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - echo Need to change directories into the PackageSource artifact directory.  The primary artifact is your working directory but we will need to move into the secondary directory to build the Docker image.
      - cd $CODEBUILD_SRC_DIR_PackagedSource
      
  build:
    commands:
      - echo Building the Docker image...   
      - docker build -t container-poc .   
      - docker tag container-poc:latest 406918538940.dkr.ecr.us-east-1.amazonaws.com/container-poc:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 406918538940.dkr.ecr.us-east-1.amazonaws.com/container-poc:latest
